features/task_11_add_files_module
voltplanner/volt pull request #14
Opened 2024-02-14 12:38 UTC by adalll

Files upload module implemented according to task https://github.com/voltplanner/volt/issues/11

2024-02-14 13:13 UTC, temarusanov commented
Add default permissions to member and admin to upload and get files in `permissions.ts`

2024-02-14 16:15 UTC, temarusanov requested changes

2024-02-14 16:18 UTC, temarusanov commented
Add default permissions to `member` and `admin` to upload and get files with `editable: false`

2024-02-16 05:54 UTC, Unvios commented on packages/server/package.json
> +    "uuid": "^9.0.1"
In node, since v15.6 there is native support for uuid V4, you can now not put extra dependencies)

`import { randomUUID } from 'crypto';`

https://nodejs.org/api/crypto.html#cryptorandomuuidoptions

2024-02-16 06:25 UTC, Unvios commented on packages/server/src/lib/modules/files/services/files.service.ts
> +            })
We read a file and put it into memory first and only then send it to S3. Can we send the data directly to S3 without uploading it into memory? If the file is large, or we have many uploads at the same time, our application will shut down due to memory overrun.

2024-04-14 06:00 UTC, merged